### ISSUE TITLE
Splitting can sometimes traceback and die

### ISSUE THREAD

**Issue by mpirnat** [mpirnat/dndme#41]
Got this while demoing...

I had split the party, then had them rejoin the main party, then tried to split again. BOOM!

```
> split Armek Dewain Lander
Traceback (most recent call last):
  File "shell.py", line 1520, in <module>
    main_loop()
  File "/Users/mike/.virtualenvs/envs/dndme/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mike/.virtualenvs/envs/dndme/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/mike/.virtualenvs/envs/dndme/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mike/.virtualenvs/envs/dndme/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "shell.py", line 1513, in main_loop
    command.do_command(*user_input[1:])
  File "shell.py", line 1225, in do_command
    source_combat.tm.remove_combatant(target)
  File "/Users/mike/Code/dndme/initiative.py", line 43, in remove_combatant
    raise Exception("Combatant not found")
Exception: Combatant not found
```

**Comment by mpirnat** [comment]
Specifically, this happens if a combat is in progress... So the sequence is:

1. split <characters>
2. start
3. switch <other combat>
4. join <first combat> <characters>
5. split <characters that were just joined>
6. Traceback!

**Comment by mpirnat** [comment]
And on a related note, when split party members join a combat in progress, they don't get merged into the turn manager/get initiative values assigned, so they never get a turn! While this might be a way to teach the lesson about "never split the party", it's probably not a fun experience, so we should fix that by giving the DM a chance to merge them into the ongoing combat with either the initiative they had from the other combat (if one was in progress) or of entering a new one (via player dice roll) if that feels more appropriate.
